### ISSUE TITLE
AppVeyor build is failing with error error CS1003: Syntax error, ',' expected

### ISSUE THREAD

**Issue by JoseASotoV** [forCrowd/WealthEconomy#136]
This issue has begun after this change in the history:

![image](https://user-images.githubusercontent.com/15162904/30350678-61c01542-97dd-11e7-855a-aa0b9374c671.png)

It is a valid change for Visual Studio but apparently AppVeyor is not accepting it, fixing this issue could be as easy as rolling back the change

**Comment by coni2k** [comment]
@JoseASotoV Thanks for pointing this one out.

I fixed couple of them but apparently there are more. I will try to check Appveyor configuration, and hopefully there might be a better way of solving this.

**Comment by coni2k** [comment]
I moved backend to Backbone project, need to check appveyor on that one:
https://github.com/forCrowd/Backbone
